### ISSUE TITLE
Deploy dotnettokyo to the group's Azure account, create deployment process

### ISSUE THREAD

**Issue by cwabbott** [cwabbott/dotnettokyo#2]
I need help deploying this! 

I will provide Azure account information via e-mail :email:  to the person that will help me deploy it :+1: 

**Goal: simply deploy the current website code to Azure, configure any server settings necessary. Stretch goal is to have some simplified automated CI + deployment process. You adivse me of any accounts that I need to setup (maybe Jenkins?)**

First person to comment can take over this issue and become our Meetup's official deployment expert :)

**Comment by darkmatterdev** [comment]
Hi Charles,

I've never done this but would like to give it a go.
Can I have the Azure account info so I can play around with it?

Thanks.

**Comment by cwabbott** [comment]
@darkmatterdev I'll get that information to you soon. Can you message me on Meetup your email address so I can share it?
(just got back from vacation so just saw this!) Thanks

**Comment by darkmatterdev** [comment]
@cwabbott Thanks for the publishing profile.  The project is published and should be live now.
http://tokyodotnet.azurewebsites.net
Let me know if you need anything else.

**Comment by cabbott** [comment]
:+1: Great, thanks!
