### ISSUE TITLE
Modify dotnettokyo code to point to our Meetup.com group

### ISSUE THREAD

**Issue by cwabbott** [cwabbott/dotnettokyo#3]
The current code apparently will display upcoming meetups, but I think it's pointed at the previous owner's Meetup.com group.

**Goal: modify any code or references to the previous Meetup.com group to point to our current group. Have it display past and upcoming meetup information.**

First person that comments below can take this issue over and help our group get a better public presence! :smile:

**Comment by Robban1980** [comment]
If no one else wants to take this one I can do it. I will give it a few more days so I am not hogging all the issues. :)

**Comment by tgrinyak** [comment]
Hi guys,
Let me look at this one

**Comment by cwabbott** [comment]
Oh great! (was on vacation, just got back to see this!)
