### ISSUE TITLE
Add a "Fork Me" banner and link to Github location

### ISSUE THREAD

**Issue by cwabbott** [cwabbott/dotnettokyo#4]
Similar to http://www.tokyorails.org/ - they have a banner in the top left which links to their github repository. In the near future I'll move this repository to a group owned repository and account, but for now we need a link so people can easily find this and everyone's activity.

**Goal: Github banner and link to this github repository.**

First one to comment below can take over this important UI update. :sunglasses:

**Comment by Robban1980** [comment]
I can start on this.

**Comment by cwabbott** [comment]
Great! :+1: Feel free to fork this repo or create a branch on this one + make a pull request

**Comment by Robban1980** [comment]
I think this was a good place for me to start. I have not worked against
Github before, only internal Git repositories. So i need to brush up on my
Github skills. :)
I think i have pushed the changes both to my fork and to the main repo :)

**Comment by cwabbott** [comment]
Cool, I see the commit in develop branch :tada: 
Will ping the group and let them know we have one update in - see if someone else will take a remaining issue :+1: 

One step closer to having a site for our meetup!
