### ISSUE TITLE
Upcoming events not listed on site

### ISSUE THREAD

**Issue by cabbott** [cwabbott/dotnettokyo#7]
Upcoming events are not listed on the site
<img width="506" alt="screen shot 2016-02-17 at 3 18 23 pm" src="https://cloud.githubusercontent.com/assets/4032197/13101403/b86cb0f2-d589-11e5-989c-27d7e5e69d6a.png">

**Comment by borrrden** [comment]
This simply looks to be disabled fwiw.  Also the signature is invalid for the URL listed in MeetupService (try accessing it with a browser)

**Comment by borrrden** [comment]
Looking into this further, I was able to query and get the results from meetup API, but I am having trouble with null reference exceptions (HttpContext.Current == null) or if I disable OutputCache on HomeController then I get "view not found"

Here is the correct URL to use -> https://api.meetup.com/Tokyo-NET-Developers-Meetup/events

**Comment by cabbott** [comment]
Thanks for looking into it Jim!
I'm catching up on things (just got back from a much needed vacation) - so bear with me if I'm slow to respond here over the next few days

**Comment by borrrden** [comment]
So it turns out the problems I were having was because Mono kind of only half implements MVC 4.  It runs fine on Windows.  FWIW I can also get it to run on Mono by not using an async method in `HomeController`

**Comment by darkmatterdev** [comment]
Let me take up this issue.
If I can complete it in time, maybe I can talk what I've done in the next meeting.

Question, what kind of info do you want to be displayed?
Below is what is returned for upcoming events.

```json
{
  "0": {
    "created": 1465281615000,
    "id": "231709906",
    "name": "Tokyo .NET Developers Meetup #12 - 2016-6-21",
    "status": "upcoming",
    "time": 1466503200000,
    "updated": 1465281615000,
    "utc_offset": 32400000,
    "waitlist_count": 0,
    "yes_rsvp_count": 7,
    "venue": {
      "id": 23880758,
      "name": "JP Tower 29F, Medidata Office",
      "lat": 0,
      "lon": 0,
      "repinned": false,
      "address_1": "2-7-2 Marunouchi, Chiyoda, Tokyo 100-0005",
      "city": "Tokyo",
      "country": "jp",
      "localized_country_name": "Japan"
    },
    "group": {
      "created": 1433397718000,
      "name": "Tokyo .NET Developers Meetup",
      "id": 18647945,
      "join_mode": "open",
      "lat": 35.66999816894531,
      "lon": 139.77000427246094,
      "urlname": "Tokyo-NET-Developers-Meetup",
      "who": "Engineers"
    },
    "link": "http://www.meetup.com/Tokyo-NET-Developers-Meetup/events/231709906/",
    "description": "<p>Tentative schedule:</p> <p><br/>19:00 Doors Open</p> <p>- food, drinks, networking</p> <p>19:30 Presentations (starting presentations earlier)</p> <p>- TBD call for presenters!</p> <p>20:50 wrap up </p> <p>\n\nWe'll fit in two or three ~10 minute presentations and leave about 45 minutes at the end for discussion, chit-chat, networking</p> ",
    "visibility": "public"
  }
}
```

**Comment by borrrden** [comment]
@darkmatterdev I have a PR outstanding for this, if you want to have a look

**Comment by darkmatterdev** [comment]
Sure!
I can see the changes in the pull request.
Is there a way to get these changes?
Do you have a fork that I can pull from?

**Comment by borrrden** [comment]
https://github.com/borrrden/dotnettokyo/tree/issue/7 

In the future to find this, you can look at the top of the PR where it says "borrrden  wants to merge 1 commit into cwabbott:develop from borrrden:issue/7"  That second part means its in a dotnettokyo repo under "borrrden" on branch "issue/7"
