### ISSUE TITLE
The Japanese version has nonlocalized texts

### ISSUE THREAD

**Issue by lschreck** [cwabbott/dotnettokyo#8]
In the Japanese language version the "No events are currently planned. Stay tuned for more info!" is still in English. This text also should be in Japanese.

**Comment by cabbott** [comment]
Thanks for posting this Laszlo!

**Comment by borrrden** [comment]
This can be closed now.  If you set up waffle.io then it will close it automatically upon seeing keywords (which is why I referenced this issue the way I did in the PR)
