### ISSUE TITLE
The website has the previous organizer's email address as contact info

### ISSUE THREAD

**Issue by lschreck** [cwabbott/dotnettokyo#9]
Both on the Japanese and English version the contact info is the previous organizer's email address.

The text resource should have the current organizer, Charles' email address, or better yet, if it's possible the site could query the meetup organizer's meetup Id through the API and make a nice link from it.

**Comment by cabbott** [comment]
Nice, thanks for submitting this issue!

**Comment by borrrden** [comment]
The second way is definitely possible, but it will require the user to create a meetup.com account if they actually want to send a message.
